config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :campaigns
      resources :cities
      resources :contacts
      resources :content_types
      resources :conversations
      resources :messages
      resources :profiles
      resources :roles
      resources :sessions
      resources :social_platforms
      resources :users

      root to: "campaigns#index"
    end

  root "landing_pages#index"
  get "/service", to: "landing_pages#service"
  get "/support", to: "landing_pages#support"
  get "/policy", to: "landing_pages#policy"
  get "/aboutus", to: "landing_pages#aboutus"
  get "messages/create"
  get "conversations/index"
  get "conversations/show"
  resource :session
  get "/auth/:provider/callback", to: "sessions#omniauth"
  get  '/complete_google_signup',  to: 'sessions#complete_google_signup',  as: :complete_google_signup
  post '/finalize_google_signup',  to: 'sessions#finalize_google_signup',  as: :finalize_google_signup

  get "/auth/failure", to: redirect("/")
  resources :passwords, param: :token
  resources :users do
    get 'confirm', on: :collection
  end
  resources :business_owners
  resources :campaigns

  # resources :influencers
  get "dashboard", to: "influencers#index", as: :dashboard
  get "influencer/profile", to: "influencers#profile", as: :influencer_profile

  resources :profiles, only: [ :create, :update, :show ]
  delete "/user/delete", to: "users#user_delete", as: :user_delete


  get "/meta_connects/connect", to: "meta_connects#connect"       # Step 1: redirect to Meta OAuth
  get "/meta_connects/callback", to: "meta_connects#callback"     # Step 2: handle callback
  get "/meta_connects/profile", to: "meta_connects#profile"       # Step 3: fetch IG profile

  get "youtube_connects/connect", to: "youtube_connects#connect"
  get "youtube_connects/callback", to: "youtube_connects#callback"
  get "youtube_connects/profile", to: "youtube_connects#profile"

  resources :twitter_connects, only: [] do
  collection do
    get :connect
    get :callback
    get :profile
  end
end

  resources :conversations, only: [:index, :show, :new, :create] do
    resources :messages, only: [:create]
  end

  get "chat", to: "conversations#index", as: :chat

  resources :contacts, only: [:new, :create]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

   match '*path', to: 'application#not_found', via: :all, constraints: lambda { |req|
    !req.path.starts_with?('/rails/active_storage')
  }
end

app/controllers/influencers_controller.rb
class InfluencersController < ApplicationController
  include ApplicationHelper
  before_action :require_influencer, only: [ :index, :profile ]
  require "ostruct"
  layout "influencer"
  def index
    @user = Current.session.user
    profile = @user.profile

    # start
    @social = @user.profile&.social_platform
    previous_version = @social&.versions&.last

    previous_attributes = previous_version ? YAML.safe_load(
      previous_version.object,
      permitted_classes: [
        Symbol,
        Date,
        Time,
        BigDecimal,
        ActiveSupport::TimeWithZone,
        ActiveSupport::TimeZone
      ],
      aliases: true  # <--- enable aliases
    ) : {}

    previous_ig = previous_attributes["ig_followers"]
    previous_yt = previous_attributes["youtube_subscriber"]
    previous_tw = previous_attributes["twitter_followers"]

    @ig_change = change_indicator(@social&.ig_followers, previous_ig)
    @yt_change = change_indicator(@social&.youtube_subscriber, previous_yt)
    @tw_change = change_indicator(@social&.twitter_followers, previous_tw)

    #end

    if profile.present?
      social = profile.social_platform

      @influencer_card = OpenStruct.new(
        email: profile.user.email_address,
        receiver_id: profile.user.id,
        photo_url: profile.profile_pic.attached? ? url_for(profile.profile_pic) : nil,
        name: profile.full_name,
        bio: profile.bio,
        ig_link: social&.ig_link,
        instagram_followers: social&.ig_followers,
        youtube_subscribers: social&.youtube_subscriber,
        twitter_followers: social&.twitter_followers,
        youtube_link: social&.youtube_link,
        twitter_link: social&.twitter_link,
        content_quality: "9",
        language: profile.language,
        category: profile.content_type,
        mobile: profile.mobile.present?,
        mobile_number: profile.mobile,
        city: profile.city&.id&.to_s,
        city_name: profile.city&.name
      )
    else
      @influencer_card = nil
    end

    @campaigns = Campaign.all.order(created_at: :desc)
    @profile = @user.profile
    @business_new = User.with_role :business_owner
    # @campaigns = User.with_role(:business_owner).joins(:campaigns).count
      if params[:city_id].present?
        @campaigns = @campaigns.where( city_id: params[:city_id]).order(created_at: :desc)
      end

      @traffic_by_city = Campaign
      .joins(:city)
      .group('cities.id')          # group by city row
      .select('cities.name AS location, COUNT(campaigns.id) AS traffic')
      .order('traffic DESC')
  end

  def profile
    @user = Current.session.user
    @profile = @user.profile || @user.build_profile
  end
end

app/helpers/influencers_helper.rb
module InfluencersHelper
end

app/views/influencers/_campaign.html.erb
<%= turbo_frame_tag "campaigns_list" do %>
  <div class="overflow-x-auto ">
    <div class="flex flex-col gap-4  max-h-[500px]">
      <% if @campaigns.any? %>
        <%= render partial: 'shared/campaign_card', collection: @campaigns, as: :campaign %>
      <% else %>
        <div class="">
          <p class="text-gray-600">No campaigns found for this city.</p>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/influencers/_city_graph.html.erb
<div class="p-6 rounded-2xl shadow-md border border-gray-200
            flex flex-col sm:flex-row items-center justify-around">

  <!-- Left side: title + donut -->
  <div class="mb-6 sm:mb-0 sm:mr-6 flex flex-col items-center">
    <h2 class="text-lg font-bold text-gray-200 mb-4">Traffic of Campaigns by Location</h2>

    <!-- Donut Chart with Stimulus -->
    <div data-controller="city-graph"
         data-city-graph-labels-value="<%= @traffic_by_city.map(&:location).to_json %>"
         data-city-graph-data-value="<%= @traffic_by_city.map(&:traffic).to_json %>"
         data-city-graph-colors-value="<%= @traffic_by_city.each_with_index.map { |_, idx| "hsl(#{idx * 360 / @traffic_by_city.size}, 70%, 50%)" }.to_json %>">

      <canvas id="donutChart" class="w-40 h-40"></canvas>
    </div>
  </div>

  <!-- Legend -->
  <div class="space-y-2 w-full sm:w-auto">
    <% total_cities = @traffic_by_city.size %>
    <% @traffic_by_city.each_with_index do |row, idx| %>
      <% hue = (idx * 360 / total_cities) %>
      <div class="flex items-center justify-between space-x-4">
        <div class="flex items-center">
          <span class="w-3 h-3 rounded-full mr-2" style="background-color: hsl(<%= hue %>, 70%, 50%)"></span>
          <span class="text-sm text-gray-100"><%= row.location %></span>
        </div>
        <span class="text-sm font-semibold text-gray-200">
          <%= number_with_precision(row.traffic, precision: 0) %>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/influencers/_form.html.erb
<turbo-frame id="profile_form">
  <%= form_with model: profile, local: false,
        class: "grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-6 p-6" do |f| %>

    <!-- Global Errors -->
    <% if profile.errors.any? %>
      <div class="mb-4 rounded-2xl bg-red-50 border border-red-200 p-4 col-span-2">
        <h2 class="text-red-700 font-semibold mb-2">
          <%= pluralize(profile.errors.count, "error") %> prevented this profile from being saved:
        </h2>
        <ul class="list-disc pl-5 text-red-600 text-sm">
          <% profile.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <!-- Profile Picture -->
    <div class="col-span-1">
      <%= f.label :profile_pic, "Profile Picture", class: "block text-sm font-medium text-gray-100" %>
      <%= f.file_field :profile_pic,
            class: "mt-2 block w-full text-sm text-gray-300
                    file:mr-4 file:py-2 file:px-4
                    file:rounded-full file:border-0 file:text-sm file:font-semibold
                    file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100" %>
    </div>

    <!-- Full Name -->
    <div>
      <%= f.label :full_name, "Full Name", class: "block text-sm font-medium text-gray-100" %>
      <%= f.text_field :full_name, placeholder: "Your Full Name",
            class: "mt-2 block w-full rounded-xl border-2 border-gray-300 shadow-sm focus:ring-blue-500 focus:border-blue-500 py-3 px-4 placeholder-gray-200" %>
      <% if profile.errors[:full_name].any? %>
        <p class="text-sm text-red-600 mt-1"><%= profile.errors[:full_name].first %></p>
      <% end %>
    </div>

    <!-- Nick Name -->
    <div>
      <%= f.label :nickname, "Nick Name", class: "block text-sm font-medium text-gray-100" %>
      <%= f.text_field :nickname, placeholder: "Your Nickname",
            class: "mt-2 block w-full rounded-xl border-2 border-gray-300 shadow-sm focus:ring-blue-500 focus:border-blue-500 py-3 px-4 placeholder-gray-200" %>
    </div>

    <!-- Bio -->
    <div>
      <%= f.label :bio, "Bio", class: "block text-sm font-medium text-gray-100" %>
      <%= f.text_area :bio, placeholder: "Your Bio",
            class: "mt-2 block w-full rounded-xl border-2 border-gray-300 shadow-sm focus:ring-blue-500 focus:border-blue-500 py-3 px-4 placeholder-gray-200 h-28" %>
    </div>

    <!-- Gender -->
    <div>
      <%= f.label :gender, "Gender", class: "block text-sm font-medium text-gray-100" %>
      <%= f.select :gender, [["Male", "male"], ["Female", "female"], ["Other", "other"]],
            { prompt: "Select Gender" },
            class: "w-full rounded-2xl border-gray-300 dark:border-gray-700
              bg-slate-900 text-white
              dark:bg-slate-900 dark:text-white
              px-4 py-4 focus:ring-2 focus:ring-blue-500 focus:border-blue-500" %>
    </div>

    <!-- Country -->
    <div>
      <%= f.label :country, "Country", class: "block text-sm font-medium text-gray-100" %>
      <%= f.text_field :country, placeholder: "Your Country",
            class: "mt-2 block w-full rounded-xl border-2 border-gray-300 shadow-sm focus:ring-blue-500 focus:border-blue-500 py-3 px-4 placeholder-gray-200" %>
    </div>

    <!-- District -->
    <div>
      <%= f.label :dist, "District", class: "block text-sm font-medium text-gray-100" %>
      <%= f.text_field :dist, placeholder: "Your District",
            class: "mt-2 block w-full rounded-xl border-2 border-gray-300 shadow-sm focus:ring-blue-500 focus:border-blue-500 py-3 px-4 placeholder-gray-200" %>
    </div>

    <!-- City -->
    <div>
      <%= f.label :city_name, "City", class: "block text-sm font-medium text-gray-700" %>
      <%= f.text_field :city_name, placeholder: "Your City",
        value: (profile.city.name if profile.city),
            class: "mt-2 block w-full rounded-xl border-2 border-gray-300 shadow-sm focus:ring-blue-500 focus:border-blue-500 py-3 px-4 placeholder-gray-400" %>
    </div>

    <!-- Language -->
    <div>
      <%= f.label :language, "Language", class: "block text-sm font-medium text-gray-100" %>
      <%= f.text_field :language, placeholder: "Your Language",
            class: "mt-2 block w-full rounded-xl border-2 border-gray-300 shadow-sm focus:ring-blue-500 focus:border-blue-500 py-3 px-4 placeholder-gray-200" %>
    </div>

    <!-- Content Type -->
    <div>
    <%= f.label :content_type, "Content Type", class: "block text-sm font-medium text-gray-100" %>
    <%= f.select :content_type,
          options_from_collection_for_select(ContentType.all, :name, :name, f.object.content_type),
          { prompt: "Select a Content Type" },
          class: "w-full rounded-2xl border-gray-300 dark:border-gray-700
              bg-slate-900 text-white
              dark:bg-slate-900 dark:text-white
              px-4 py-4 focus:ring-2 focus:ring-blue-500 focus:border-blue-500" %>

    <% if profile.errors[:content_type].any? %>
      <p class="text-sm text-red-600 mt-1"><%= profile.errors[:content_type].first %></p>
    <% end %>
  </div>


    <!-- Mobile Number -->
    <div>
      <%= f.label :mobile, "Mobile Number", class: "block text-sm font-medium text-gray-100" %>
      <%= f.text_field :mobile, placeholder: "Your Mobile Number",
            class: "mt-2 block w-full rounded-xl border-2 border-gray-300 shadow-sm focus:ring-blue-500 focus:border-blue-500 py-3 px-4 placeholder-gray-200" %>
      <% if profile.errors[:mobile].any? %>
        <p class="text-sm text-red-600 mt-1"><%= profile.errors[:mobile].first %></p>
      <% end %>
    </div>

    <!-- Submit -->
    <div class="col-span-1 md:col-span-2">
      <%= f.submit "Save Profile",
            class: "w-full py-3 px-6 rounded-md text-lg text-white transition-transform transform hover:scale-105", style: "background: linear-gradient(135deg, #9333ea, #6d28d9);" %>
    </div>

  <% end %>
</turbo-frame>

app/views/influencers/_profile_progress.html.erb
<% completeness = profile.completeness_percentage %>
<% progress_color =
    if completeness == 100
      "bg-green-500 text-green-100 border-green-500"
    elsif completeness < 50
      "bg-red-500 text-red-100 border-red-500"
    else
      "bg-primary text-primary-content border-primary"
    end %>

<div
  class="radial-progress border-4 <%= progress_color %>"
  style="--value:<%= completeness %>;"
  aria-valuenow="<%= completeness %>"
  role="progressbar">
  <%= completeness %>%
</div>

app/views/influencers/_social_media.html.erb
<div class="max-w-4xl mx-auto space-y-4 p-4">

  <!-- Instagram Item -->
  <div class="p-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 rounded-xl shadow-md bg-slate-900/50">
    <div class="flex items-center space-x-4">
      <i class="fab fa-instagram text-4xl text-instagram"></i>
      <span class="text-lg font-medium text-gray-300">Instagram</span>
    </div>
    <div class="text-gray-200">
      <% if @profile.social_platform&.ig_followers.present? %>
        <%= human_count(@profile.social_platform.ig_followers) %> Followers
      <% else %>
        N/A
      <% end %>
    </div>
    <%= link_to "Connect Instagram", meta_connects_connect_path,
        class: "bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-6 rounded-full transition duration-200 text-center w-full sm:w-auto"
    %>
  </div>

  <!-- X (Twitter) Item -->
  <div class="p-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 rounded-xl shadow-md bg-slate-900/50">
    <div class="flex items-center space-x-4">
      <i class="fab fa-x-twitter text-4xl text-x"></i>
      <span class="text-lg font-medium text-gray-300">X (Twitter)</span>
    </div>
    <div class="text-gray-200">
      <% if @profile.social_platform&.twitter_followers.present? %>
        <%= human_count(@profile.social_platform.twitter_followers) %> Followers
      <% else %>
        N/A
      <% end %>
    </div>
    <%= link_to "Connect Twitter", connect_twitter_connects_path,
        class: "bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-6 rounded-full transition duration-200 text-center w-full sm:w-auto"
    %>
  </div>

  <!-- YouTube Item -->
  <div class="p-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 rounded-xl shadow-md bg-slate-900/50">
    <div class="flex items-center space-x-4">
      <i class="fab fa-youtube text-4xl text-youtube"></i>
      <span class="text-lg font-medium text-gray-300">YouTube</span>
    </div>
    <div class="text-gray-200">
      <% if @profile.social_platform&.youtube_subscriber.present? %>
        <%= human_count(@profile.social_platform.youtube_subscriber) %> Subscribers
      <% else %>
        N/A
      <% end %>
    </div>
    <%= link_to "Connect Youtube", youtube_connects_connect_path,
        class: "bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-6 rounded-full transition duration-200 text-center w-full sm:w-auto"
    %>
  </div>

</div>

app/views/influencers/form.turbo_stream.erb
<turbo-stream target="profile_form" action="replace">
  <template>
    <%= render partial: "influencers/form", locals: { profile: @profile }, formats: [:html] %>
  </template>
</turbo-stream>

app/views/influencers/index.html.erb
<% content_for :title, "Dashboard | Influencer Connect" %>
<div class="max-w-7xl mx-auto p-5">
    <!-- Dashboard Header -->
    <header class="flex flex-col sm:flex-row justify-between items-center mb-6">
        <h1 class="text-3xl font-bold text-gray-100 mb-2 sm:mb-0">Overview</h1>
        <div class="flex items-center space-x-2 text-gray-600 text-sm">
        </div>
    </header>

    <!-- Top row of summary cards -->
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-6">
        <!-- Card 1: Views -->
        <div class="p-6 rounded-2xl shadow-md border border-gray-200">
            <div class="flex items-center justify-between mb-4">
                <h2 class="text-sm font-semibold text-gray-300">IG Follower</h2>

                <i class="fa-brands fa-instagram text-xl"></i>
            </div>
            <div class="flex items-end">
                <span class="text-3xl font-bold text-gray-300 mr-2">
                    <% if @profile&.social_platform&.ig_followers.present? %>
                        <%= human_count(@profile.social_platform.ig_followers) %>
                            <% else %>
                                N/A
                                <% end %>
                </span>

                <% if @ig_change.is_a?(Hash) %>
                    <span
                        class="text-xs font-semibold text-<%= @ig_change[:color] %>-500 bg-<%= @ig_change[:color] %>-100 px-2 py-1 rounded-full">
                        <%= @ig_change[:text] %>
                    </span>
                    <% else %>
                        <span class="text-xs font-semibold text-gray-500 bg-gray-100 px-2 py-1 rounded-full">
                            N/A
                        </span>
                        <% end %>

            </div>
        </div>

        <!-- Card 2: Visits -->
        <div class="text-slate-900/50 p-6 rounded-2xl shadow-md border border-gray-200">
            <div class="flex items-center justify-between mb-4">
                <h2 class="text-sm font-semibold text-gray-500">Youtube</h2>
                <i class="fa-brands fa-youtube text-purple-500 text-xl hover:text-red-500"></i>
            </div>
            <div class="flex items-end">
                <span class="text-3xl font-bold text-gray-300 mr-2">
                    <% if @profile&.social_platform&.youtube_subscriber.present? %>
                        <%= human_count(@profile.social_platform.youtube_subscriber) %>
                            <% else %>
                                N/A
                                <% end %>
                </span>
                <% if @yt_change.is_a?(Hash) %>
                    <span
                        class="text-xs font-semibold text-<%= @yt_change[:color] %>-500 bg-<%= @yt_change[:color] %>-100 px-2 py-1 rounded-full">
                        <%= @yt_change[:text] %>
                    </span>
                    <% else %>
                        <span class="text-xs font-semibold text-gray-500 bg-gray-100 px-2 py-1 rounded-full">
                            N/A
                        </span>
                        <% end %>
            </div>
        </div>

        <!-- Card 3: twitter -->
        <div class="text-slate-900/50 p-6 rounded-2xl shadow-md border border-gray-200">
            <div class="flex items-center justify-between mb-4">
                <h2 class="text-sm font-semibold text-gray-500">Twitter</h2>
                <i class="fa-brands fa-twitter text-blue-500 text-xl hover:text-red-500"></i>
            </div>
            <div class="flex items-end">
                <span class="text-3xl font-bold text-gray-300 mr-2">
                    <% if @profile&.social_platform&.twitter_followers.present? %>
                        <%= human_count(@profile.social_platform.twitter_followers) %>
                            <% else %>
                                N/A
                                <% end %>
                </span>
                <% if @tw_change.is_a?(Hash) %>
                    <span
                        class="text-xs font-semibold text-<%= @tw_change[:color] %>-500 bg-<%= @tw_change[:color] %>-100 px-2 py-1 rounded-full">
                        <%= @tw_change[:text] %>
                    </span>
                    <% else %>
                        <span class="text-xs font-semibold text-gray-500 bg-gray-100 px-2 py-1 rounded-full">
                            N/A
                        </span>
                        <% end %>
            </div>
        </div>



        <!-- Card 4: New Users (similar to 3) -->
        <div class="text-slate-900/50 p-6 rounded-2xl shadow-md border border-gray-200">
            <div class="flex items-center justify-between mb-4">
                <h2 class="text-sm font-semibold text-gray-500">Total Promotion</h2>
                <i class="fas fa-chart-line text-green-500 text-xl"></i>
            </div>
            <div class="flex items-end">
                <span class="text-3xl font-bold text-gray-300 mr-2">
                    <%= @campaigns.count %>
                </span>
                <span class="text-xs font-semibold text-green-500 bg-green-100 px-2 py-1 rounded-full">+6.07%</span>
            </div>
        </div>
    </div>

    <!-- Middle row of charts -->
    <div class="grid grid-cols-1 lg:grid-cols-1 gap-6 mb-6">
        <!-- Left chart: Total Users line graph -->
        <div class="text-slate-900/50 rounded-2xl shadow-md border border-gray-200 ">
            <div >
                <div class="p-3 flex md:flex-row flex-col items-start md:items-center md:justify-between justify-start gap-2 pb-4 border-b border-gray-200">
                    <div>
                        <h2 class="text-2xl sm:text-3xl font-bold text-gray-300">
                            Live Campaign
                        </h2>
                    </div>
                    <div>
                        <span
                            class="inline-flex items-center rounded-full bg-green-100 px-3 py-1 text-sm font-medium text-green-800 ring-1 ring-inset ring-green-600/20 shadow-md">
                            <svg class="w-2 h-2 mr-1 animate-pulse" fill="currentColor" viewBox="0 0 8 8">
                                <circle cx="4" cy="4" r="3" />
                            </svg>
                            LIVE
                        </span>
                    </div>
                    <div class="flex items-center justify-center">
                        <%= form_with url: dashboard_path, method: :get, class: "" , data: { turbo_frame: "_top" ,
                            turbo_action: "replace" } do |f| %>

                            <div class="relative w-full sm:w-auto">
                                <%= select_tag :city_id, options_from_collection_for_select(City.order(:name), :id,
                                    :name, params[:city_id]), prompt: "Select All City" ,
                                    class: "w-full rounded-2xl border-gray-300 dark:border-gray-700
                                            bg-slate-900 text-white
                                            dark:bg-slate-900 dark:text-white
                                            px-4 py-4 focus:ring-2 focus:ring-blue-500 focus:border-blue-500", onchange: "this.form.submit();" %>
                            </div>
                            <% end %>
                    </div>
                </div>
            </div>

            <div class="flex items-center justify-center">
                <%=render 'campaign' %>
            </div>
        </div>
    </div>

    <!-- Bottom row of charts -->
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
        <!-- Right chart: Traffic by Website -->
        <div class="p-6 rounded-2xl shadow-md border border-gray-200">
            <h2 class="text-lg font-bold text-gray-300 mb-4">Influencer Profile Overview</h2>
            <!-- List of websites with bar indicators -->
            <div class="space-y-4">
                <% if @influencer_card.present? %>
                    <%= render partial: "business_owners/influencer_card" , locals: { influencer:
                        @influencer_card,owner:true } %>
                        <% else %>
                            <p class="text-gray-500 text-center">No influencer data available.</p>
                            <% end %>
            </div>

        </div>
        <!-- Right chart: Traffic by Location -->
        <%=render 'city_graph' %>
    </div>
</div>

app/views/influencers/profile.html.erb
<% content_for :title, "Your Profile | Influencer Connect" %>
<div class="flex-grow p-8">
    <div class="max-w-4xl mx-auto">
        <div class="p-8">
            <!-- Header Section -->
            <div class="flex items-center justify-between flex-wrap mb-6">
                <div class="flex items-center justify-center gap-5">
                <turbo-frame id="profile_progress">
                    <%= render "influencers/profile_progress", profile: @profile %>
                </turbo-frame>

                    <div>
                        <div>
                            <span class="text-lg font-semibold text-gray-100">Profile Completion</span>
                            <div class="text-gray-300 text-sm"><%= @profile.completeness_percentage %> completed</div>
                        </div>
                    </div>
                </div>
                <div class="flex items-center space-x-6">
                    <% if @profile.profile_pic.attached? %>

                        <%= image_tag @profile.profile_pic.variant(resize_to_fill: [150, 150]).processed,
                            class: "shadow-md w-20 h-20 rounded-full object-cover" %>
                            <%else%>
                                <img class="w-20 h-20 rounded-full object-cover"
                                    src="https://placehold.co/100x100/A020F0/FFFFFF?text=A" alt="User profile photo">
                                <% end %>
                                    <div>
                                        <h2 class="text-2xl font-semibold text-gray-100">
                                            <%= @user.profile&.full_name %>
                                        </h2>
                                        <p class="text-gray-300 text-base">
                                            <%= @user.email_address %>
                                        </p>
                                    </div>
                </div>
                <%# link_to "Edit" , profile_path,
                    class: "mt-4 sm:mt-0 bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-6 rounded-xl shadow-md transition-colors duration-200"
                    %>
            </div>

            <hr class="border-t border-gray-200 my-8">

            <!-- Form Section -->
             <turbo-frame id="profile_form">
                <%= render "influencers/form", profile: @profile, formats: [:html] %>
             </turbo-frame>

                    <hr class="border-t border-gray-200 my-8">

                    <!-- Email Section -->
                    <div>
                        <h3 class="text-lg font-semibold text-gray-100 mb-4">My email Address</h3>
                        <div class="flex items-center space-x-4 bg-slate-900/50 rounded-xl p-4 border border-gray-200">
                            <i class="fas fa-envelope text-blue-600 text-xl"></i>
                            <div>
                                <p class="font-medium text-gray-100">
                                    <%= @user.email_address %>
                                </p>
                                <p class="text-gray-500 text-sm">
                                    <%= time_ago_in_words(@user.created_at) %> ago
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="mt-5">
                        <%= button_to "Permanent Delete" , user_delete_path, method: :delete, data: {
                            confirm: "Are you sure? This action cannot be undone." },
                            class: "btn bg-red-500 text-white rounded-xl hover:bg-red-300" %>

                    </div>
        </div>
    </div>

    <div class="flex flex-col max-w-4xl mt-5 mx-auto">
        <div class="">
            <h1 class="mb-4 text-3xl font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-6xl"><span
                    class="text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">Social</span>
                Media connect</h1>
        </div>
        <div>
            <%=render "social_media" %>
        </div>
    </div>
</div>