config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :campaigns
      resources :cities
      resources :contacts
      resources :content_types
      resources :conversations
      resources :messages
      resources :profiles
      resources :roles
      resources :sessions
      resources :social_platforms
      resources :users

      root to: "campaigns#index"
    end

  root "landing_pages#index"
  get "/service", to: "landing_pages#service"
  get "/support", to: "landing_pages#support"
  get "/policy", to: "landing_pages#policy"
  get "/aboutus", to: "landing_pages#aboutus"
  get "messages/create"
  get "conversations/index"
  get "conversations/show"
  resource :session
  get "/auth/:provider/callback", to: "sessions#omniauth"
  get  '/complete_google_signup',  to: 'sessions#complete_google_signup',  as: :complete_google_signup
  post '/finalize_google_signup',  to: 'sessions#finalize_google_signup',  as: :finalize_google_signup

  get "/auth/failure", to: redirect("/")
  resources :passwords, param: :token
  resources :users do
    get 'confirm', on: :collection
  end
  resources :business_owners
  resources :campaigns

  # resources :influencers
  get "dashboard", to: "influencers#index", as: :dashboard
  get "influencer/profile", to: "influencers#profile", as: :influencer_profile

  resources :profiles, only: [ :create, :update, :show ]
  delete "/user/delete", to: "users#user_delete", as: :user_delete


  get "/meta_connects/connect", to: "meta_connects#connect"       # Step 1: redirect to Meta OAuth
  get "/meta_connects/callback", to: "meta_connects#callback"     # Step 2: handle callback
  get "/meta_connects/profile", to: "meta_connects#profile"       # Step 3: fetch IG profile

  get "youtube_connects/connect", to: "youtube_connects#connect"
  get "youtube_connects/callback", to: "youtube_connects#callback"
  get "youtube_connects/profile", to: "youtube_connects#profile"

  resources :twitter_connects, only: [] do
  collection do
    get :connect
    get :callback
    get :profile
  end
end

  resources :conversations, only: [:index, :show, :new, :create] do
    resources :messages, only: [:create]
  end

  get "chat", to: "conversations#index", as: :chat

  resources :contacts, only: [:new, :create]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

   match '*path', to: 'application#not_found', via: :all, constraints: lambda { |req|
    !req.path.starts_with?('/rails/active_storage')
  }
end

app/views/shared/_campaign_card.html.erb
<%# _campaign_card.html.erb - expects local variable `campaign` %>

<div class="bg-slate-900/50  hover:border border-gray-100  rounded-2xl shadow-sm p-5 flex flex-col md:flex-row items-start gap-4">
  <!-- left: image / icon -->
  <div class="flex-shrink-0">
    <!-- replace with real image if you have one -->
    <div class="w-20 h-20 rounded-xl bg-slate-900/90 dark:bg-gray-700 flex items-center justify-center text-gray-300">
      <i class="fa-solid fa-briefcase"></i>
    </div>
  </div>

  <!-- middle: details -->
  <div class="flex-1">
    <div class="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
      <div>
        <h3 class="text-lg font-semibold text-gray-200 dark:text-gray-100"><%= campaign.content_type.presence || "Campaign" %></h3>
        <p class="text-sm text-gray-300 mt-1"><%= campaign.deliverable_details %></p>
      </div>

      <div class="text-right mt-2 md:mt-0">
        <span class="inline-block text-xs px-2 py-1 rounded-full bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-300 font-medium">
          <%= campaign.created_at.strftime("%b %d, %Y") %>
        </span>
      </div>
    </div>

    <div class="mt-3 grid grid-cols-1 md:grid-cols-2 gap-3">
      <div>
        <p class="text-xs text-gray-200 uppercase tracking-wide">Messages</p>
        <p class="mt-1 text-sm text-gray-300 dark:text-gray-200"><%= truncate(campaign.key_messages.to_s, length: 140) %></p>
      </div>

      <div>
        <p class="text-xs text-gray-200 uppercase tracking-wide">Guidelines</p>
        <p class="mt-1 text-sm text-gray-300 dark:text-gray-200"><%= truncate(campaign.creative_guidelines.to_s, length: 140) %></p>
      </div>

      <div>
        <p class="text-xs text-gray-200 uppercase tracking-wide">City</p>
        <p class="mt-1 text-sm text-gray-300 dark:text-gray-200"><%= truncate(campaign.city.name.to_s, length: 140) %></p>
      </div>
    </div>

    <div class="mt-3 flex flex-wrap gap-2">
      <% tags = campaign.tags_require.to_s.split(",").map(&:strip).reject(&:blank?) %>
      <% tags.each do |t| %>
        <span class="text-xs px-2 py-1 rounded-full border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900/40 text-gray-700 dark:text-gray-200">
          <%= t %>
        </span>
      <% end %>
    </div>

    <div class="mt-4 text-sm text-gray-500 flex flex-col md:flex-row gap-6">
      <div>
        <div class="font-medium text-gray-200 dark:text-gray-200">Approval</div>
        <div><%= campaign.approval_deadline&.strftime("%b %d, %Y %I:%M %p") %></div>
      </div>

      <div>
        <div class="font-medium text-gray-200 dark:text-gray-200">Posting Start</div>
        <div><%= campaign.posting_start_date&.strftime("%b %d, %Y %I:%M %p") %></div>
      </div>

      <div>
        <% unless local_assigns[:owner] %>
        <div class="font-medium text-gray-200 dark:text-gray-200">Email</div>
        <div>
          <%= campaign.user.email_address %>
          <%= form_with url: conversations_path, method: :post, data: { turbo: false }, class: "space-y-2 mt-1" do %>
            <%= hidden_field_tag "conversation[receiver_id]", campaign.user.id %>
            <%= submit_tag "Start Chat",
                class: "px-2 py-2 rounded-full  w-full rounded-xl  text-lg text-white transition-transform transform hover:scale-105", style: "background: linear-gradient(135deg, #9333ea, #6d28d9);" %>
          <% end %>

        </div>
        <% end %>
      </div>
    </div>
  </div>

  <!-- right: actions -->
  <div class="flex-shrink-0 self-stretch flex flex-row md:flex-col items-start md:items-end justify-between mt-4 md:mt-0 gap-2">
    <div class="flex gap-2 md:flex-col">
      <% if local_assigns[:owner] %>
      <%= link_to "View", campaign_path(campaign), class: "inline-flex items-center px-3 py-1.5 rounded-xl border border-gray-200  text-sm font-medium hover:bg-yellow-500 dark:hover:bg-gray-700/50" %>
      <%= link_to "Edit", edit_campaign_path(campaign), class: "inline-flex items-center px-3 py-1.5 rounded-xl  text-lg text-white transition-transform transform hover:scale-105", style: "background: linear-gradient(135deg, #9333ea, #6d28d9);" %>
      <%= button_to "Delete", campaign_path(campaign), method: :delete, data: { confirm: "Are you sure?" }, class: "inline-flex items-center px-3 py-1.5 rounded-xl bg-red-600 text-white text-sm font-medium hover:bg-red-700" %>
      <% end %>
    </div>

    <div class="text-xs text-gray-400 mt-2">
      <%= time_ago_in_words(campaign.created_at) %> ago
    </div>
  </div>
</div>

app/views/shared/_chat_icon.html.erb
<div class="cursor-pointer">
  <%= link_to chat_path, class: "flex items-center justify-center px-8 py-4 rounded-full font-bold text-lg text-white transition-transform transform hover:scale-105", style: "background: linear-gradient(135deg, #9333ea, #6d28d9);" do %>
    <%= image_tag "chat.png", alt: "Scroll Up", class: "h-5 w-5" %>
  <%end%>
</div>

app/views/shared/_city_dropdown.html.erb
<%# select_tag :city, options_for_select(["Select City", "Ahmedabad", "Rajkot", "Jamnagar"], params[:city]), class: "block appearance-none w-full bg-white border border-gray-300 text-gray-700 py-3 px-4 pr-8 rounded-full leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>


<%= select_tag :city_id,
      options_from_collection_for_select(City.order(:name), :id, :name, params[:city_id]),
      prompt: "Select City",
      class: "w-full rounded-2xl border-gray-300 dark:border-gray-700
              bg-slate-900 text-white
              dark:bg-slate-900 dark:text-white
              px-4 py-4 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
       %>

app/views/shared/_flash.html.erb
<!-- shared/_flash.html.erb -->
     <div data-controller="flash" class="toast toast-top toast-end z-[9999] mt-[100px]">
      <% flash.each do |type, message| %>
        <div class="alert <%= flash_class(type) %> shadow-lg">
          <span><%= message %></span>
        </div>
      <% end %>
    </div>

app/views/shared/_footer.html.erb
<footer class="footer footer-horizontal footer-center bg-base-700 text-white  p-10 border-t border-base-300 mt-10">
  <nav class="grid grid-flow-col gap-4">
    <a class="link link-hover">About us</a>
    <a class="link link-hover">Contact</a>
    <a href="#" class="link link-hover">Company</a>
  </nav>
  <nav>
    <div class="grid grid-flow-col gap-4">
      <a>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          class="fill-current">
          <path
            d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path>
        </svg>
      </a>
      <a>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          class="fill-current">
          <path
            d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path>
        </svg>
      </a>
      <a>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          class="fill-current">
          <path
            d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path>
        </svg>
      </a>
    </div>
  </nav>
  <aside>
    <p>Copyright © <%=Time.now.year%> - All right reserved by Influencer Connect</p>
  </aside>
</footer>

app/views/shared/_influencer_navbar.html.erb
<div class="bg-slate-900/50 w-20 flex-shrink-0 rounded-r-3xl flex flex-col items-center py-6 space-y-8 h-screen sticky top-0">
  <a href="/dashboard" class="text-2xl p-3 rounded-lg transition-colors duration-200
    <%= 'bg-white text-black' if controller_name == 'influencers'  && action_name == 'index' %>">
    <i class="fas fa-th"></i>
  </a>

  <!-- <a href="#" class="text-2xl p-3 rounded-lg transition-colors duration-200
    <%# 'bg-white text-black' if controller_name == 'time_logs' %>">
    <i class="far fa-clock"></i>
  </a> -->

  <a href="/influencer/profile" class="text-2xl p-3 rounded-lg transition-colors duration-200
    <%= 'bg-white text-black' if controller_name == 'influencers' && action_name == 'profile' %>">
    <i class="far fa-user"></i>
  </a>

  <a href="/chat" class="text-2xl p-3 rounded-lg transition-colors duration-200
    <%= 'bg-white text-black' if controller_name == 'conversations'  %>">
    <i class="far fa-comments"></i>
  </a>

  <!-- <a href="#" class="text-2xl p-3 rounded-lg transition-colors duration-200
    <%# 'bg-white text-black' if controller_name == 'settings' %>">
    <i class="fas fa-cog"></i>
  </a> -->

  <%= button_to session_path, method: :delete, class:"text-2xl p-3 rounded-lg hover:bg-white hover:text-black hover:bg-opacity-30 transition-colors duration-200" do %>
    <i class="fa-solid fa-arrow-right-from-bracket"></i>
  <% end %>
</div>

app/views/shared/_loader.html.erb
<div id="loader" data-loader-target="loader"
  class="hidden fixed inset-0 flex items-center justify-center bg-white/70 z-50">
  <div class="animate-spin rounded-full h-12 w-12 border-t-4 border-blue-500 border-solid"></div>
</div>

app/views/shared/_navbar.html.erb
<header
  data-controller="navbar"
  data-navbar-target="header"
  class="container mx-auto px-6 py-4 font-sans flex justify-between items-center sticky top-5 z-50 bg-transparent transition-colors duration-300">

  <!-- Logo -->
  <div class="flex items-center space-x-2 ">
    <div class="h-8 w-8 rounded-full bg-gradient-to-r from-primary via-yellow-400 to-accent-light"></div>
    <a href="/"
      class="text-xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-primary via-yellow-400 to-accent-light">
      INFLUENCERTRACK
    </a>
  </div>


  <!-- Desktop Navigation -->
  <nav class="hidden lg:flex items-center space-x-8 text-white font-medium capitalize font-sans" data-navbar-target="text">
    <a href="/service" class="hover:text-blue-600 <%= 'border-b-2 border-blue-600 text-blue-600' if controller_name == 'landing_pages' && action_name == 'service' %>">Service</a>
    <a href="/support" class="hover:text-blue-600 <%= 'border-b-2 border-blue-600 text-blue-600' if controller_name == 'landing_pages' && action_name == 'support' %>">Support</a>
    <a href="/aboutus" class="hover:text-blue-600 <%= 'border-b-2 border-blue-600 text-blue-600' if controller_name == 'landing_pages' && action_name == 'aboutus' %>">About Us</a>
    <a href="/policy" class="hover:text-blue-600 <%= 'border-b-2 border-blue-600 text-blue-600' if controller_name == 'landing_pages' && action_name == 'policy' %>">policy</a>
  </nav>

  <!-- Desktop Auth Buttons -->
  <% unless authenticated? %>
    <div class="hidden lg:flex items-center space-x-4 font-medium">
      <%= link_to "Sign In", new_session_path, class: "cursor-pointer inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-10 px-4 py-2 border border-input bg-background hover:bg-yellow-500 hover:text-white-foreground" %>
      <%= link_to new_user_path do %>
        <button class="px-6 py-2 font-bold rounded-md text-lg text-white transition-transform transform hover:scale-105" style="background: linear-gradient(135deg, #9333ea, #6d28d9);">Start Free</button>
      <% end %>
    </div>
  <% else %>
    <div class="hidden lg:flex items-center space-x-4 font-medium">
      <%= button_to "Log out",
      session_path,
      method: :delete,
      class: "cursor-pointer inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-10 px-4 py-2 border border-input bg-background hover:bg-yellow-500 hover:text-white-foreground" %>

      <% if @user&.has_role?(:business_owner) %>
        <%= button_to "Find Influencers", business_owners_path, method: :get, class: "cursor-pointer inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition transform hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-10 px-4 py-2 bg-gradient-to-r from-indigo-500 to-purple-600 text-white shadow-md hover:shadow-xl" %>
        <%= button_to "Campaign", campaigns_path, method: :get, class: "cursor-pointer inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition transform hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-10 px-4 py-2 bg-gradient-to-r from-indigo-500 to-purple-600 text-white shadow-md hover:shadow-xl" %>
      <% end %>

      <% if @user&.has_role?(:influencer) %>
        <%= button_to "Dashboard", dashboard_path, method: :get, class: "cursor-pointer inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition transform hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-10 px-4 py-2 bg-gradient-to-r from-indigo-500 to-purple-600 text-white shadow-md hover:shadow-xl" %>
      <% end %>

      <% if @user&.has_role?(:admin) %>
        <%= button_to "Dashboard", admin_campaigns_path, method: :get, class: "cursor-pointer inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition transform hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-10 px-4 py-2 bg-gradient-to-r from-indigo-500 to-purple-600 text-white shadow-md hover:shadow-xl" %>
      <% end %>
    </div>
  <% end %>

  <!-- Mobile Hamburger -->
  <button data-action="click->navbar#toggle" class="lg:hidden p-2 cursor-pointer text-gray-700 rounded-md focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500">
    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"/>
    </svg>
  </button>


  <!-- Mobile Menu -->
  <div data-navbar-target="menu" class="hidden lg:hidden flex-col space-y-4 px-6 py-4 bg-slate-900 shadow-md absolute top-20 left-0 right-0 z-40">
      <div class="flex flex-col items-center justify-center">
        <a href="/service" class="hover:text-blue-600 text-blue-500">Service</a>
        <a href="/support" class="hover:text-blue-600 text-blue-500">Support</a>
        <a href="/aboutus" class="hover:text-blue-600 text-blue-500">About Us</a>
        <a href="/policy" class="hover:text-blue-600 text-blue-500">policy</a>
      </div>
    <% unless authenticated? %>
    <div class="flex flex-col items-center justify-center space-y-4 mt-4">
          <%= link_to "Sign In", new_session_path, class: "w-full cursor-pointer inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition transform hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-10 px-4 py-2 bg-gradient-to-r from-indigo-500 to-purple-600 text-white shadow-md hover:shadow-xl" %>
    </div>

    <% else %>
      <%= button_to "Log out", session_path, method: :delete, class: "w-full cursor-pointer inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition transform hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-10 px-4 py-2 bg-gradient-to-r from-indigo-500 to-purple-600 text-white shadow-md hover:shadow-xl" %>

      <% if @user&.has_role?(:business_owner) %>
        <%= button_to "Find Influencers", business_owners_path, method: :get, class: "w-full cursor-pointer inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition transform hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-10 px-4 py-2 bg-gradient-to-r from-indigo-500 to-purple-600 text-white shadow-md hover:shadow-xl" %>
        <%= button_to "Campaign", campaigns_path, method: :get, class: "w-full cursor-pointer inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition transform hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-10 px-4 py-2 bg-gradient-to-r from-indigo-500 to-purple-600 text-white shadow-md hover:shadow-xl" %>
      <% end %>

      <% if @user&.has_role?(:influencer) %>
        <%= button_to "Dashboard", dashboard_path, method: :get, class: "w-full cursor-pointer inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition transform hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-10 px-4 py-2 bg-gradient-to-r from-indigo-500 to-purple-600 text-white shadow-md hover:shadow-xl" %>
      <% end %>

      <% if @user&.has_role?(:admin) %>
        <%= button_to "Dashboard", admin_campaigns_path, method: :get, class: "w-full cursor-pointer inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition transform hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-10 px-4 py-2 bg-gradient-to-r from-indigo-500 to-purple-600 text-white shadow-md hover:shadow-xl" %>
      <% end %>
    <% end %>
  </div>
</header>

app/views/shared/_up_scroll.html.erb
<div data-controller="scroll" class="cursor-pointer">
  <button data-action="click->scroll#scrollUp" class="flex items-center justify-center px-8 py-4 rounded-full font-bold text-lg text-white transition-transform transform hover:scale-105" style="background: linear-gradient(135deg, #9333ea, #6d28d9);">
    <%= image_tag "up_icon1.png", alt: "Scroll Up", class: "h-5 w-5" %>
  </button>
</div>